site_name: AXBot QQ机器人
site_url: https://axiangcoding.github.io/axbot-qq-docs

repo_url: https://github.com/axiangcoding/axbot-qq-docs/
edit_uri: blob/main/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: images/favicon.ico
  custom_dir: overrides
  language: zh
  font: false
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.suggest
    - social
    - announce.dismiss
    - navigation.footer
    - content.action.edit

nav:
  - index.md
  - sponsor.md
  - report.md
  - 用户指南:
      - user-guide/how-to-use.md
      - user-guide/axbot-credit.md
  - 命令列表:
      - command-list/base-cmd.md
      - command-list/funny-cmd.md
      - command-list/wt-cmd.md
      - command-list/qq-group.md
      - command-list/subscribe-cmd.md
  - 数据介绍:
      - data-intro/wt-player-data.md
  - roadmap.md


markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
